### ISSUE TITLE
Create database models

### ISSUE THREAD

**Issue by andela-marika** [andela/bp-esa-backend#1]
Create the database models for the project.

Refer to the ERD diagram below:  
![erd](https://user-images.githubusercontent.com/24455941/42444157-0c44ec1e-8378-11e8-97a3-3c889826fede.png)

**Comment by machariamarigi** [comment]
https://github.com/andela/bp-esa-backend/tree/create-database-models/server/models

**Comment by andela-marika** [comment]
![erd 1](https://user-images.githubusercontent.com/24455941/42625248-f4068680-85cf-11e8-967d-19f72314e779.png)

**Comment by machariamarigi** [comment]
Is there a difference between parnerID and uniqueid
<img width="165" alt="screen shot 2018-07-16 at 11 16 01" src="https://user-images.githubusercontent.com/17122597/42748677-b17645ae-88e9-11e8-907c-283d78c34323.png">
