### ISSUE TITLE
Email Integration

### ISSUE THREAD

**Issue by machariamarigi** [andela/bp-esa-backend#25]
## Description
Integrate an email service with the application to automate sending of emails for onboarding/offboarding fellows.

### Dev Notes

- SMTP library used is [NodeMailer](https://nodemailer.com/about/).

**Comment by machariamarigi** [comment]
I noticed that for the email integration to work with Gmail we need to set up Oath2 authentication with the account that is supposed to send the emails. I'll need help with this.
cc @Kelechukwu @andela-marika

**Comment by Kelechukwu** [comment]
@machariamarigi, which account are you using to send the emails?  Can you implement with your personal Gmail pending when this is resolved ?
